name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"



dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.1
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  
  intl: ^0.18.1

  http: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
test_api: ^0.7.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/kitaplar/
    - assets/data/kitaplar.json
    - assets/images/obpd.png
